# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy

on:
  workflow_dispatch:
    inputs:
        logLevel:
          description: 'Log level'     
          required: true
          default: 'warning'
        tags:
          description: 'Test scenario tags'  
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm ci
      - run: npm test
      - name: deploy
        run: |
          npx ncc build index.js
          zip -j deploy.zip ./dist/*
          aws lambda update-function-code --function-name=test-lambda-node-js --zip-file=fileb://deploy.zip
